/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/0qHnqbBDqNC
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Detail() {
  return (
    <div className="bg-background min-h-screen flex flex-col items-center justify-center">
      <article className="bg-background rounded-lg shadow-lg overflow-hidden w-full max-w-3xl">
        <div className="relative h-64 sm:h-80 md:h-96">
          <img
            src="/placeholder.svg"
            alt="Article Image"
            width={1200}
            height={600}
            className="w-full h-full object-cover"
            style={{ aspectRatio: "1200/600", objectFit: "cover" }}
          />
        </div>
        <div className="p-6 md:p-8">
          <div className="flex items-center mb-4 space-x-4">
            <div className="flex items-center space-x-2 text-muted-foreground">
              <UserIcon className="w-4 h-4" />
              <span>John Doe</span>
            </div>
            <div className="flex items-center space-x-2 text-muted-foreground">
              <CalendarIcon className="w-4 h-4" />
              <span>August 3, 2024</span>
            </div>
            <div className="flex items-center space-x-2 text-muted-foreground">
              <ClockIcon className="w-4 h-4" />
              <span>5 min read</span>
            </div>
          </div>
          <h1 className="text-3xl font-bold mb-4">Taxing Laughter: The Joke Tax Chronicles</h1>
          <p className="text-muted-foreground mb-6">
            Once upon a time, in a far-off land, there was a very lazy king who spent all day lounging on his throne.
            One day, his advisors came to him with a problem: the kingdom was running out of money.
          </p>
          <p className="text-muted-foreground mb-6">
            Jokester began sneaking into the castle in the middle of the night and leaving jokes all over the place:
            under the king&apos;s pillow, in his soup, even in the royal toilet. The king was furious, but he
            couldn&apos;t seem to stop Jokester.
          </p>
          <p className="text-muted-foreground mb-6">
            And then, one day, the people of the kingdom discovered that the jokes left by Jokester were so funny that
            they couldn&apos;t help but laugh. And once they started laughing, they couldn&apos;t stop.
          </p>
          <p className="text-muted-foreground mb-6">
            The king thought long and hard, and finally came up with a brilliant plan: he would tax the jokes in the
            kingdom.
          </p>
          <blockquote className="border-l-4 border-muted pl-4 text-muted-foreground mb-6">
            &ldquo;After all,&rdquo; he said, &ldquo;everyone enjoys a good joke, so it&apos;s only fair that they
            should pay for the privilege.&rdquo;
          </blockquote>
          <h2 className="text-2xl font-bold mb-4">The Joke Tax</h2>
          <p className="text-muted-foreground mb-6">
            The king&apos;s subjects were not amused. They grumbled and complained, but the king was firm:
          </p>
          <ul className="list-disc pl-6 text-muted-foreground mb-6">
            <li>1st level of puns: 5 gold coins</li>
            <li>2nd level of jokes: 10 gold coins</li>
            <li>3rd level of one-liners : 20 gold coins</li>
          </ul>
          <p className="text-muted-foreground mb-6">
            As a result, people stopped telling jokes, and the kingdom fell into a gloom. But there was one person who
            refused to let the king&apos;s foolishness get him down: a court jester named Jokester.
          </p>
        </div>
      </article>
    </div>
  )
}

function CalendarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


function ClockIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <polyline points="12 6 12 12 16 14" />
    </svg>
  )
}


function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}
